import { SourceDirectory, SourceFile, type Children } from "@alloy-js/core";

/**
 * Renders the mock scaffolding files: IInitializer, Initializer, and MockRegistration.
 */
export function MockScaffolding(props: { interfaceRegistrations: string[] }): Children {
  return (
    <SourceDirectory path="mocks">
      <SourceFile filetype="cs" path="IInitializer.cs">
        {getInitializerInterface()}
      </SourceFile>
      <SourceFile filetype="cs" path="Initializer.cs">
        {getInitializerImplementation()}
      </SourceFile>
      {props.interfaceRegistrations.length > 0 && (
        <SourceFile filetype="cs" path="MockRegistration.cs">
          {getMockRegistration(props.interfaceRegistrations)}
        </SourceFile>
      )}
    </SourceDirectory>
  );
}

function getInitializerInterface(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

namespace TypeSpec.Helpers
{
    public interface IInitializer
    {
        object? Initialize(System.Type type);
        T Initialize<T>() where T : class, new();
    }
}`;
}

function getInitializerImplementation(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

namespace TypeSpec.Helpers
{
    public class Initializer : IInitializer
    {
        public Initializer(IDictionary<Type, object?> cache)
        {
            Cache = cache;
        }

        internal virtual IDictionary<Type, object?> Cache { get; }

        internal object? CacheAndReturn(Type type, object? instance)
        {
            Cache[type] = instance;
            return instance;
        }

        public object? Initialize(Type type)
        {
            if (Cache.ContainsKey(type)) return Cache[type];
            if (type == typeof(string)) return CacheAndReturn(type, string.Empty);
            if (type == typeof(int)) return CacheAndReturn(type, 0);
            if (type == typeof(long)) return CacheAndReturn(type, 0L);
            if (type == typeof(double)) return CacheAndReturn(type, 0.0);
            if (type == typeof(bool)) return CacheAndReturn(type, false);
            if (type == typeof(DateTime)) return CacheAndReturn(type, DateTime.UtcNow);
            if (type == typeof(DateTimeOffset)) return CacheAndReturn(type, DateTimeOffset.UtcNow);
            if (type == typeof(TimeSpan)) return CacheAndReturn(type, TimeSpan.Zero);
            if (type.IsArray)
            {
                var element = type.GetElementType();
                if (element == null) return null;
                return CacheAndReturn(type, Array.CreateInstance(element, 0));
            }
            if (type.IsClass) return InitializeClass(type);
            if (type.IsEnum) return CacheAndReturn(type, Enum.GetValues(type).GetValue(0));
            return new object();
        }

        public T Initialize<T>() where T : class, new()
        {
            var result = new T();
            var initialized = InitializeClass(typeof(T), result);
            return initialized as T ?? result;
        }

        private object? InitializeClass(Type type, object? instance = null)
        {
            if (Cache.ContainsKey(type)) return Cache[type];
            var result = instance ?? Activator.CreateInstance(type);
            foreach (var property in type.GetProperties())
            {
                if (property.CanWrite)
                {
                    property.SetValue(result, Initialize(property.PropertyType));
                }
            }
            return CacheAndReturn(type, result);
        }
    }
}`;
}

function getMockRegistration(interfaceRegistrations: string[]): string {
  const registrations = interfaceRegistrations
    .map((r) => `            builder.Services.AddScoped<${r}>();`)
    .join("\n");

  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Http.Features;

namespace TypeSpec.Helpers
{
    public static class MockRegistration
    {
        public static void Register(WebApplicationBuilder builder)
        {
            builder.Services.AddHttpContextAccessor();
            builder.Services.AddScoped<IJsonSerializationProvider, JsonSerializationProvider>();
            builder.Services.AddSingleton<IDictionary<Type, object?>>(new Dictionary<Type, object?>());
            builder.Services.AddScoped<IInitializer, Initializer>();
${registrations}
            builder.Services.Configure<FormOptions>(options =>
            {
                options.MemoryBufferThreshold = int.MaxValue;
                options.MultipartBodyLengthLimit = int.MaxValue;
            });
        }
    }
}`;
}
