import { code, SourceFile, type Children } from "@alloy-js/core";

const csharpFileHeader = code`
  // Generated by @typespec/http-server-csharp
  // <auto-generated />
  #nullable enable
`;

export interface CSharpFileProps {
  /** Path of the source file */
  path: string;

  /** Source file content */
  children?: Children;
}

/**
 * A C# source file that automatically includes the auto-generated header.
 * Use this for all static C# files in the http-server-csharp emitter.
 */
export function CSharpFile(props: CSharpFileProps): Children {
  return (
    <SourceFile filetype="cs" path={props.path} header={csharpFileHeader}>
      {props.children}
    </SourceFile>
  );
}
