import { code, type Children } from "@alloy-js/core";

/**
 * Renders the standard auto-generated file header for C# source files.
 * Include this as the first child in any C# source file emitted by this package.
 */
export function SourceFileHeader(): Children {
  return code`
    // Generated by @typespec/http-server-csharp
    // <auto-generated />
    #nullable enable${"\n"}
  `;
}
