import { SourceDirectory, SourceFile, type Children } from "@alloy-js/core";

/**
 * Renders the JSON serialization helper files (converters and provider).
 * These are static C# source files used by the generated models and controllers.
 */
export function JsonConverters(): Children {
  return (
    <SourceDirectory path="lib">
      <SourceFile filetype="cs" path="TimeSpanDurationConverter.cs">
        {getTimeSpanDurationConverter()}
      </SourceFile>
      <SourceFile filetype="cs" path="Base64UrlJsonConverter.cs">
        {getBase64UrlJsonConverter()}
      </SourceFile>
      <SourceFile filetype="cs" path="UnixEpochDateTimeConverter.cs">
        {getUnixEpochDateTimeConverter()}
      </SourceFile>
      <SourceFile filetype="cs" path="HttpServiceExceptionFilter.cs">
        {getHttpServiceExceptionFilter()}
      </SourceFile>
      <SourceFile filetype="cs" path="JsonSerializationProvider.cs">
        {getJsonSerializationProvider()}
      </SourceFile>
    </SourceDirectory>
  );
}

function getTimeSpanDurationConverter(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;

namespace TypeSpec.Helpers.JsonConverters
{
    public class TimeSpanDurationConverter : JsonConverter<TimeSpan>
    {
        public override TimeSpan Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return XmlConvert.ToTimeSpan(reader.GetString()!);
        }

        public override void Write(Utf8JsonWriter writer, TimeSpan value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(XmlConvert.ToString(value));
        }
    }
}`;
}

function getBase64UrlJsonConverter(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TypeSpec.Helpers.JsonConverters
{
    public class Base64UrlJsonConverter : JsonConverter<byte[]>
    {
        public override byte[] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? base64Url = reader.GetString();
            if (base64Url == null) return Array.Empty<byte>();
            string base64 = base64Url.Replace('-', '+').Replace('_', '/');
            switch (base64.Length % 4)
            {
                case 2: base64 += "=="; break;
                case 3: base64 += "="; break;
            }
            return Convert.FromBase64String(base64);
        }

        public override void Write(Utf8JsonWriter writer, byte[] value, JsonSerializerOptions options)
        {
            string base64 = Convert.ToBase64String(value);
            string base64Url = base64.Replace('+', '-').Replace('/', '_').TrimEnd('=');
            writer.WriteStringValue(base64Url);
        }
    }
}`;
}

function getUnixEpochDateTimeConverter(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TypeSpec.Helpers.JsonConverters
{
    public class UnixEpochDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            long unixTime = reader.GetInt64();
            return DateTimeOffset.FromUnixTimeSeconds(unixTime);
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            writer.WriteNumberValue(value.ToUnixTimeSeconds());
        }
    }
}`;
}

function getHttpServiceExceptionFilter(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace TypeSpec.Helpers
{
    public class HttpServiceExceptionFilter : IExceptionFilter
    {
        public void OnException(ExceptionContext context)
        {
            context.Result = new ObjectResult(new { error = context.Exception.Message })
            {
                StatusCode = 500
            };
            context.ExceptionHandled = true;
        }
    }
}`;
}

function getJsonSerializationProvider(): string {
  return `// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;

namespace TypeSpec.Helpers
{
    public interface IJsonSerializationProvider
    {
        JsonSerializerOptions Options { get; }
    }

    public class JsonSerializationProvider : IJsonSerializationProvider
    {
        public JsonSerializerOptions Options { get; }

        public JsonSerializationProvider()
        {
            Options = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                Converters = {
                    new JsonStringEnumConverter(),
                    new TimeSpanDurationConverter(),
                    new Base64UrlJsonConverter(),
                    new UnixEpochDateTimeOffsetConverter()
                }
            };
        }
    }
}`;
}
